### ISSUE TITLE
Unable to login using 'az login'

### ISSUE THREAD

**Issue by 158945204-myseneca** [CSP451-2237/CSP451-Public#1]
When trying to use az login, the following message appears....

The command failed with an unexpected error. Here is the traceback:
9. The ID token already expires. Make sure your computer's time and time zone are both correct. Current epoch = 1696314768.  The id_token was: {
  "aud": "04b07795-8ddb-461a-bbee-02f9e1bf7b46",
  "iss": "https://login.microsoftonline.com/ed27b597-cea0-4942-8c6f-40e6a78bf47d/v2.0",
  "iat": 1696303659,
  "nbf": 1696303659,
  "exp": 1696307559,
  "aio": "AWQAm/8UAAAAH6Mb4TNNsOjEaB4dbvxsSevJI6M1eUS304Q+MO99C+9iofmplLvWGadbxGbLDW0CnZJZ2lXQQA38MjpnIEiiCSYN+1Esu1PsoHa0z6UENFBQMRcO3BZDasr18FsX8pUK",
  "name": "ODL_User 1088917",
  "nonce": "d0266dbf1205ee026da775783e11de5f5f12ebed9951e49d16782dd0ddcc6823",
  "oid": "ac1044e4-74b5-4eac-8616-9ce10b682383",
  "preferred_username": "odl_user_1088917@seneca-csp451nia.cloudlabs.ai",
  "puid": "10032002F7A05474",
  "rh": "0.AX0Al7Un7aDOQkmMb0Dmp4v0fZV3sATbjRpGu-4C-eG_e0a1AL0.",     
  "sub": "HephzywItCt4gARqSW70Dywis2g0Q5V6cRE-6ap7t8M",
  "tid": "ed27b597-cea0-4942-8c6f-40e6a78bf47d",
  "uti": "3mWTEvhH7EKN5H2hLykyAA",
  "ver": "2.0"
}
Traceback (most recent call last):
  File "/opt/az/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/command_modules/profile/custom.py", line 139, in login
    subscriptions = profile.login(
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/_profile.py", line 154, in login
    user_identity = identity.login_with_auth_code(scopes=scopes, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/auth/identity.py", line 153, in login_with_auth_code
    result = self._msal_app.acquire_token_interactive(
  File "/opt/az/lib/python3.10/site-packages/msal/application.py", line 1861, in acquire_token_interactive
    response = _clean_up(self.client.obtain_token_by_browser(
  File "/opt/az/lib/python3.10/site-packages/msal/oauth2cli/oidc.py", line 281, in obtain_token_by_browser
    return super(Client, self).obtain_token_by_browser(
  File "/opt/az/lib/python3.10/site-packages/msal/oauth2cli/oauth2.py", line 639, in obtain_token_by_browser
    return self._obtain_token_by_browser(
  File "/opt/az/lib/python3.10/site-packages/msal/oauth2cli/oauth2.py", line 677, in _obtain_token_by_browser
    return self.obtain_token_by_auth_code_flow(
  File "/opt/az/lib/python3.10/site-packages/msal/application.py", line 153, in obtain_token_by_auth_code_flow
    return super(_ClientWithCcsRoutingInfo, self).obtain_token_by_auth_code_flow(
  File "/opt/az/lib/python3.10/site-packages/msal/oauth2cli/oidc.py", line 205, in obtain_token_by_auth_code_flow
    result = super(Client, self).obtain_token_by_auth_code_flow(      
  File "/opt/az/lib/python3.10/site-packages/msal/oauth2cli/oauth2.py", line 547, in obtain_token_by_auth_code_flow
    return self._obtain_token_by_authorization_code(
  File "/opt/az/lib/python3.10/site-packages/msal/oauth2cli/oauth2.py", line 731, in _obtain_token_by_authorization_code
    return self._obtain_token("authorization_code", data=data, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/msal/oauth2cli/oidc.py", line 116, in _obtain_token
    ret = super(Client, self)._obtain_token(grant_type, *args, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/msal/oauth2cli/oauth2.py", line 788, in _obtain_token
    (on_obtaining_tokens or self.on_obtaining_tokens)({
  File "/opt/az/lib/python3.10/site-packages/msal/application.py", line 707, in <lambda>
    on_obtaining_tokens=lambda event: self.token_cache.add(dict(      
  File "/opt/az/lib/python3.10/site-packages/msal/token_cache.py", line 317, in add
    super(SerializableTokenCache, self).add(event, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/msal/token_cache.py", line 128, in add
    return self.__add(event, now=now)
  File "/opt/az/lib/python3.10/site-packages/msal/token_cache.py", line 158, in __add
    decode_id_token(id_token, client_id=event["client_id"]) if id_token else {})
  File "/opt/az/lib/python3.10/site-packages/msal/oauth2cli/oidc.py", line 77, in decode_id_token
    raise RuntimeError("%s Current epoch = %s.  The id_token was: %s" % (
RuntimeError: 9. The ID token already expires. Make sure your computer's time and time zone are both correct. Current epoch = 1696314768.  The id_token was: {
  "aud": "04b07795-8ddb-461a-bbee-02f9e1bf7b46",
  "iss": "https://login.microsoftonline.com/ed27b597-cea0-4942-8c6f-40e6a78bf47d/v2.0",
  "iat": 1696303659,
  "nbf": 1696303659,
  "exp": 1696307559,
  "aio": "AWQAm/8UAAAAH6Mb4TNNsOjEaB4dbvxsSevJI6M1eUS304Q+MO99C+9iofmplLvWGadbxGbLDW0CnZJZ2lXQQA38MjpnIEiiCSYN+1Esu1PsoHa0z6UENFBQMRcO3BZDasr18FsX8pUK",
  "name": "ODL_User 1088917",
  "nonce": "d0266dbf1205ee026da775783e11de5f5f12ebed9951e49d16782dd0ddcc6823",
  "oid": "ac1044e4-74b5-4eac-8616-9ce10b682383",
  "preferred_username": "odl_user_1088917@seneca-csp451nia.cloudlabs.ai",
  "puid": "10032002F7A05474",
  "rh": "0.AX0Al7Un7aDOQkmMb0Dmp4v0fZV3sATbjRpGu-4C-eG_e0a1AL0.",     
  "sub": "HephzywItCt4gARqSW70Dywis2g0Q5V6cRE-6ap7t8M",
  "tid": "ed27b597-cea0-4942-8c6f-40e6a78bf47d",
  "uti": "3mWTEvhH7EKN5H2hLykyAA",
  "ver": "2.0"
}
To check existing issues, please visit: https://github.com/Azure/azure-cli/issues

**Comment by 158945204-myseneca** [comment]
![image](https://github.com/CSP451-2237/CSP451-Public/assets/107362418/f63cc33c-c6b9-4176-b4f0-b936fad595f6)

![image](https://github.com/CSP451-2237/CSP451-Public/assets/107362418/f84364c3-47eb-48a4-8e76-89074bbcdbb7)

**Comment by 158945204-myseneca** [comment]
Fixed this error by forcing the WSL client to sync with my laptop

sudo hwclock -s
